points:
  zones:
    matrix:
      columns:
        outer1:
          rows:
            upper:
              row_net: P0
              column_net: P4
              diode_net: D2
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P4
              diode_net: D3
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P4
              diode_net: D4
              tags: 
                1u: true
                15u: false
        outer:
          spread: 18
          rows:
            upper:
              row_net: P0
              column_net: P5
              diode_net: D5
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P5
              diode_net: D6
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P5
              diode_net: D7
              tags: 
                1u: true
                15u: false
        pinky:
          spread: 18
          stagger: 2
          rows:
            upper:
              row_net: P0
              column_net: P6
              diode_net: D8
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P6
              diode_net: D9
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P6
              diode_net: D10
              tags: 
                1u: true
                15u: false
        ring:
          spread: 18
          stagger: 2
          rows:
            upper:
              row_net: P0
              column_net: P7
              diode_net: D11
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P7
              diode_net: D12
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P7
              diode_net: D13
              tags: 
                1u: true
                15u: false
        middle:
          spread: 18
          stagger: 1
          rows:
            upper:
              row_net: P0
              column_net: P8
              diode_net: D14
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P8
              diode_net: D15
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P8
              diode_net: D16
              bind: [0, 56, 0, 0]
              tags: 
                1u: true
                15u: false
        point:
          spread: 18
          stagger: -2
          rows:
            upper:
              row_net: P0
              column_net: P9
              diode_net: D17
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P9
              diode_net: D18
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P9
              diode_net: D19
              tags: 
                1u: true
                15u: false
        inner:
          spread: 18
          stagger: -1
          rows:
            upper:
              row_net: P0
              column_net: P10
              diode_net: D20
              bind: [0, 25, 0, 0]
              tags: 
                1u: true
                15u: false
            home:
              row_net: P1
              column_net: P10
              diode_net: D21
              bind: [3, 25, 0, 0]
              tags: 
                1u: true
                15u: false
            lower:
              row_net: P2
              column_net: P10
              diode_net: D22
              bind: [3, 25, 0, 0]
              tags: 
                1u: true
                15u: false
      rows:
        lower.padding: 17
        home.padding: 17
        upper.padding: 17
      key:
        footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =row_net
              to: =diode_net
            params:
                keycaps: true
                reverse: true
                hotswap: true
          diode:
            type: diode
            nets:
              from: =diode_net
              to: =column_net
            anchor:
              shift: [6.0,-7.0]
              rotate: 180
          diode_via: 
            type: via
            nets:
              net: =column_net
            anchor:
              shift: [8.0,-5.5]
    thumb:
      anchor:
        ref: matrix_inner_lower
        shift: [6,-30]
      columns:
        first: 
          rotate: -24
          stagger: 2
          rows:
            bottom:
              skip: true
            top:
              rotate: 90
              skip: false
              row_net: P3
              column_net: P6
              diode_net: D23
              bind: [30, 10, 20, 0]
              tags: 
                15u: true
        second:
          spread: 20
          stagger: -5.2
          rotate: -4
          rows:
            bottom:
              row_net: P3
              column_net: P8
              diode_net: D24
              spacing: 2
              shift: [0,2]
              tags: 
                1u: true
                15u: false
            top:
              row_net: P3
              column_net: P7
              diode_net: D25
              tags: 
                1u: true
                15u: false
              bind: [0, 0, 0.5, 60]
        third:
          spread: 20.5
          stagger: 4
          rotate: -5
          rows:
            bottom:
              skip: true
            top:
              rotate: 90
              skip: false
              row_net: P3
              column_net: P9
              diode_net: D26
              bind: [1, 5, 0, 5]
              tags: 
                15u: true
      rows:
        top.padding: 18
      key:
        footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =row_net
              to: =diode_net
            params:
                keycaps: true
                reverse: true
                hotswap: true
          diode:
            type: diode
            nets:
              from: =diode_net
              to: =column_net
            anchor:
              shift: [6.0,-7.0]
              rotate: 180
          diode_via: 
            type: via
            nets:
              net: =column_net
            anchor:
              shift: [8.0,-5.5]
    ext_thumb:
      anchor: 
        ref: matrix_inner_lower
        shift: [18,-1]
      columns:
        only:
          rows:
            only:
              row_net: P3
              diode_net: D27
              column_net: P10
              bind: [0, 1, 10, 0]
              tags: 
                1u: true
                15u: false
      key:
        footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =row_net
              to: =diode_net
            params:
                keycaps: true
                reverse: true
                hotswap: true
          diode:
            type: diode
            nets:
              from: =diode_net
              to: =column_net
            anchor:
              shift: [6.0,-7.0]
              rotate: 180
          diode_via: 
            type: via
            nets:
              net: =column_net
            anchor:
              shift: [8.0,-5.5]
    ext_thumb_lower:
      anchor: 
        ref: matrix_middle_lower
        shift: [-2,-25]
      columns:
        left:
          rows:
            only:
              rotate: -4
              row_net: P3
              column_net: P4
              diode_net: D28
              bind: [0, 1, 10, 0]
              tags: 
                1u: true
                15u: false
        right:
          rows:
            only:
              rotate: -13.5
              shift: [2.5,-3.4]
              row_net: P3
              column_net: P5
              diode_net: D29
              bind: [0, 1, 10, 0]
              tags: 
                1u: true
                15u: false
      key:
        footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =row_net
              to: =diode_net
            params:
                keycaps: true
                reverse: true
                hotswap: true
          diode:
            type: diode
            nets:
              from: =diode_net
              to: =column_net
            anchor:
              shift: [6.0,-7.0]
              rotate: 180
          diode_via: 
            type: via
            nets:
              net: =column_net
            anchor:
              shift: [8.0,-5.5]
outlines:
  exports:
    keys1:
      - type: keys
        side: left
        tags: [1u]
        size: [cx-0.5, cy-0.5]
        bound: false
    keys5:
      - type: keys
        side: left
        tags: [15u]
        size: [1.5cx-0.5, cy-0.5]
        bound: false
pcbs:
  flutter_v2_wren:
    outlines:
      main:
        outline: keys1
        layer: Eco1.User
      caps15:
        outline: keys5
        layer: Eco1.User
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: matrix_inner_upper
          shift: [21, -5.25]
          rotate: -90
        params:
          orientation: down
      reset_button:
          type: b3u1000p
          nets:
            r1: RST
            r2: GND
          anchor:
            ref: matrix_inner_upper
            shift: [8,10]
            rotate: 0
      power_switch:
          type: pcm12
          nets:
            from: pos
            to: RAW
          anchor:
            ref: ext_thumb_only_only
            shift: [15.5,-5.5]
            rotate: 90
          params:
            reverse: true
      jst:
          type: bat
          nets: 
            pos: pos
            neg: GND
          anchor:
            ref: ext_thumb_only_only
            shift: [-4,10]
